version: '3.8'

services:
  web:
    build: .
    ports:
      - "8000:8000"
    environment:
      - DJANGO_SETTINGS_MODULE=hrSystem.settings
    depends_on:
      - db

  db:
    image: postgres:13
    environment:
      - POSTGRES_DB=hrdb
      - POSTGRES_USER=hruser
      - POSTGRES_PASSWORD=hrpass