pipeline {
    agent any
    
    environment {
        PYTHON_VERSION = '3.9'
        DJANGO_SETTINGS_MODULE = 'hrSystem.settings'
    }
    
    stages {
        stage('Setup') {
            steps {
                sh 'python3 -m pip install --upgrade pip'
                sh 'pip install -r requirements.txt -r requirements_test.txt'
            }
        }
        
        stage('Test') {
            steps {
                sh 'python3 manage.py migrate'
                sh 'python3 manage.py behave --format html-pretty --out reports/behave'
                sh 'python3 manage.py test'
            }
            post {
                always {
                    junit '**/test-reports/*.xml'
                    publishHTML target: [
                        allowMissing: true,
                        alwaysLinkToLastBuild: true,
                        keepAll: true,
                        reportDir: 'reports/behave',
                        reportFiles: 'index.html',
                        reportName: 'BDD Report'
                    ]
                }
            }
        }
        
        stage('Deploy') {
            when {
                branch 'main'
            }
            steps {
                sh 'docker build -t hr-system .'
                sh 'docker-compose up -d'
            }
        }
    }
}